### ISSUE TITLE
Ability to mock events

### ISSUE THREAD

**Issue by Jethril** [Serg046/AutoFake#224]
I tried to call the compiler-generated method "add_XXX" but unfortunately the compiler prevents me from doing it.

Also thanks a lot for providing effort into making free libraries like this. C# has a very poor mocking support.

**Comment by Serg046** [comment]
I think it is possible to support but what is a use case? An event is just a regular delegate with extended syntax,  no logic inside. It looks like mocking something on event handlers side is a better idea.

**Comment by Jethril** [comment]
Here is a concrete example: I had to write `Process.WaitForExitAsync()` by myself (because I was using .NET Standard 2.0).  
I needed to mock the `Process` class, and triggered the `Exited` event handler to test if the returned `Task` was completed:
```cs
var process = new Process();
var fake = new Fake(typeof(ProcessUtils));
var sut = fake.Rewrite(() => ProcessUtils.WaitForExitAsync(process));

sut.Replace((Process p) => p.EnableRaisingEvents).Return(true);
sut.Replace((Process p) => p.HasExited).Return(false);

var task = sut.Execute();

sut.Replace((Process p) => p.HasExited).Return(true);

// Remove this trick once issue https://github.com/Serg046/AutoFake/issues/224 is resolved.
var onExited = (EventHandler?) typeof(Process)
    .GetField("_onExited", BindingFlags.Instance | BindingFlags.NonPublic)
    !.GetValue(process);

onExited?.Invoke(process, EventArgs.Empty);

// Check that the task is completed.
await task.Timeout(1_000);
```

**Comment by Serg046** [comment]
Sounds like it is impossible to help here. You cannot act with AutoFake same way as with classic mockers. If you did something like `var fake = new Fake<Process>();` you would never get normal `Process` instance anymore. AutoFake will rewrite it so that it will be another type Process -> ProcessFake therefore you would not able to pass it to your `WaitForExitAsync`.

There are some tests here https://github.com/Serg046/AutoFake/blob/master/Tests/AutoFake.FunctionalTests/InstanceTests/SelfReferenceTests.cs#L16, as you can see when you try to get the fake instance, you get InvalidCastException.

However, if Process was an abstract class, you would be able to use classic mockers to mock it and then pass to `WaitForExitAsync` but unfortunately that's not your case. If you see how we can try to solve it, feel free to share it here,

**Comment by Jethril** [comment]
I understand the way it works, and that's why the base concept behind your library is brillant.

However, I have a poor understanding of what you can do when rewriting / generating IL. I suppose that you already generate the code required to register / remove the events, because I was able to register a handler.  
Perhaps you could substitute the compiler-generated methods (`add_XXX`, `remove_XXX`) by something like this:
```cs
// Inside SomeClass

// Added to the IL when rewriting.
public List<EventHandler> XXX_Handlers = new List<EventHandler>();

// Rewritten.
public void add_XXX(EventHandler handler)
{
    XXX_Handlers.Add(handler);
}

// Rewritten.
public void remove_XXX(EventHandler handler)
{
    XXX_Handlers.Remove(handler);
}
```

Then you may access the added property list through reflection when the user invokes, e.g:
```cs
var fake = new Fake<SomeClass>();
var sut = fake.Rewrite(() => ...);

var event = sut.ReplaceEvent(p => p.XXX);

// One possibility would be to register a delegate to listen for additions / removals.
event.HandlerAdded += (handler) => ...;
event.HandlerRemoved += (handler) => ...;

// Another one would be to use expectations.
event.ExpectedHandlers(2);

sut.Execute();

// Finally, we may trigger the events by ourselves:
event.Invoke(EventArgs.Empty);
```

I think you could also replace the list by a custom class, which may be a kind of state machine that allows you to perform the actions and register the expectations.
Would it be possible?

**Comment by Serg046** [comment]
I'd focus on features that are impossible to achieve using existing libs. Reflection works fine here, I don't see a big need to duplicate it even though you might have a better/convenient contract to use. However, you highlighted missing feature which might be useful, there is no support for += and -= syntax which are actually add_XXX and remove_XXX, we can add support for these exact calls so that you can do something like this:

```csharp
class Program
{
    public static void Main()
    {
        var fake = new Fake<ProcessUtils>();
        var sut = fake.Rewrite(f => f.WaitForExitAsync(new Process()));
        sut.Verify((Process proc) => proc.add_Exited(Arg.Is<Action>(HandleArgument)));
        sut.Execute();
    }

    public static bool HandleArgument(Action act)
    {
        act(); // So you can actually do with the argument whatever you might want
        return true;
    }

    class Process
    {
        //Let's imagine this is accessible (AutoFake will do this somehow)
        public void add_Exited(Action eventHandler) { }
    }

    class ProcessUtils
    {
        public void WaitForExitAsync(Process process)
        {
            //process.Exited += () => Console.WriteLine("Event happened");
            process.add_Exited(() => Console.WriteLine("Event happened"));
        }
    }
}
```
As a bonus this will allow other operations like replacements, removals, inserts, etc.

In addition, AutoFake is very flexible and extensible, it is 100% covered by IoC, all the services are accessible via `someFake.Services` so that you can replace any implementation and you are not locked to AutoFake contract. I am going to describe all the concepts soon, at least briefly.

**Comment by Jethril** [comment]
Oh, ok,
That would be also useful. Do you want me to close this issue and open another one with subject "add += operators"?

**Comment by Serg046** [comment]
No need for such a bureaucracy, I will do the change here soon. We just need to find some idea for syntax as you cannot do something like that:
```csharp
var fake = new Fake<Process>();
var sut = fake.Rewrite(p => p.WaitForExitAsync(CancellationToken.None));
sut.Verify(f => f.Exited += (s, e) => { });
```
Maybe something like that then:
```csharp
var fake = new Fake<Process>();
var sut = fake.Rewrite(p => p.WaitForExitAsync(CancellationToken.None));
sut.Verify(() => Event.AddHandler(Arg.Is<EventHandler>(...)));
sut.Verify(() => Event.RemoveHandler(Arg.Is<EventHandler>(...)));

public static class Event
{
    public static void AddHandler<T>(T handler) {}
    public static void RemoveHandler<T>(T handler) { }
}
```

**Comment by Serg046** [comment]
Released:
```csharp
public static void Main()
{
    var fake = new Fake<Helper>();
    var sut = fake.Rewrite(f => f.WaitForExitAsync(new Process()));
    //sut.Verify(Event.Of<Process>(nameof(Process.Exited)).Add(() => Arg.IsAny<EventHandler>()));
    sut.Verify(Event.Of<Process>(nameof(Process.Exited)).Add(() => Arg.Is<EventHandler>(HandleArgument)));
    sut.Execute();
}

static bool HandleArgument(EventHandler handler)
{
    handler("some sender", EventArgs.Empty);
    return true;
}

class Helper
{
    public void WaitForExitAsync(Process process)
    {
        process.Exited += (s, e) => Console.WriteLine($"Triggered with sender '{s}' and event args '{e}'");
    }
}
```
